"""
data/database.py
─────────────────
AtlasFX database layer.

Defines the full schema using SQLAlchemy ORM (Core + ORM mixed).
Supports SQLite for development and PostgreSQL for production.

Tables:
    ohlcv              — Historical and live price bars
    signals            — All generated trade signals
    trades             — All executed and paper trades
    strategy_registry  — Strategy metadata and live status
    risk_events        — Risk threshold breaches
    daily_snapshots    — Daily equity and performance snapshots
    notifications_log  — Sent notifications

Usage:
    from data.database import init_db, get_session
    init_db()
    with get_session() as session:
        ...
"""

from __future__ import annotations

import uuid
from contextlib import contextmanager
from datetime import datetime
from typing import Generator, Optional

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    Integer,
    String,
    Text,
    UniqueConstraint,
    create_engine,
    event,
    text,
)
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from logs.logger import get_logger

log = get_logger(__name__)

# ── Engine setup ──────────────────────────────────────────────────────────────

_engine = None
_SessionFactory = None


def _get_database_url() -> str:
    """Resolve the database URL from settings."""
    from config.settings import settings

    if settings.database_url:
        return settings.database_url

    db_path = settings.db_path
    db_path.parent.mkdir(parents=True, exist_ok=True)
    return f"sqlite:///{db_path}"


def get_engine():
    """Return the SQLAlchemy engine (creates it on first call)."""
    global _engine
    if _engine is None:
        url = _get_database_url()
        connect_args = {}
        if url.startswith("sqlite"):
            connect_args["check_same_thread"] = False

        _engine = create_engine(
            url,
            connect_args=connect_args,
            echo=False,  # Set True to log all SQL in development
        )

        # Enable WAL mode for SQLite — improves concurrent read/write
        if url.startswith("sqlite"):
            @event.listens_for(_engine, "connect")
            def set_sqlite_pragma(dbapi_connection, connection_record):
                cursor = dbapi_connection.cursor()
                cursor.execute("PRAGMA journal_mode=WAL")
                cursor.execute("PRAGMA foreign_keys=ON")
                cursor.close()

        log.info("database_engine_created", url=url.split("///")[-1])
    return _engine


def get_session_factory() -> sessionmaker:
    """Return the session factory (creates it on first call)."""
    global _SessionFactory
    if _SessionFactory is None:
        _SessionFactory = sessionmaker(bind=get_engine(), expire_on_commit=False)
    return _SessionFactory


@contextmanager
def get_session() -> Generator[Session, None, None]:
    """
    Context manager providing a database session.

    Automatically commits on success, rolls back on exception.

    Usage:
        with get_session() as session:
            session.add(record)
    """
    factory = get_session_factory()
    session = factory()
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()


# ── ORM Base ──────────────────────────────────────────────────────────────────

class Base(DeclarativeBase):
    pass


# ── Models ────────────────────────────────────────────────────────────────────

class OHLCV(Base):
    """
    OHLCV price bars for all instruments and timeframes.

    The combination of (instrument, timeframe, timestamp) is unique.
    Timestamps are always UTC.
    """
    __tablename__ = "ohlcv"
    __table_args__ = (
        UniqueConstraint("instrument", "timeframe", "timestamp"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    instrument = Column(String(20), nullable=False, index=True)
    timeframe = Column(String(5), nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False, index=True)
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Float, nullable=True)  # Not available for all FX sources
    source = Column(String(50), nullable=True)  # e.g. 'yfinance', 'oanda'
    created_at = Column(DateTime, default=datetime.utcnow)

    def __repr__(self) -> str:
        return (
            f"<OHLCV {self.instrument} {self.timeframe} "
            f"{self.timestamp} C={self.close}>"
        )


class TradeSignal(Base):
    """
    All signals generated by strategies, whether acted on or not.

    Recording rejected signals is important for post-hoc analysis
    and identifying filter effectiveness.
    """
    __tablename__ = "signals"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    strategy_id = Column(String(100), nullable=False, index=True)
    instrument = Column(String(20), nullable=False, index=True)
    timeframe = Column(String(5), nullable=False)
    direction = Column(String(4), nullable=False)    # BUY or SELL
    entry_price = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=False)
    take_profit = Column(Float, nullable=False)
    confidence = Column(Float, nullable=False)       # 0.0 to 1.0
    timestamp = Column(DateTime, nullable=False, index=True)
    acted_on = Column(Boolean, default=False)
    rejection_reason = Column(String(200), nullable=True)
    metadata_json = Column(Text, nullable=True)      # JSON string
    created_at = Column(DateTime, default=datetime.utcnow)

    def __repr__(self) -> str:
        return (
            f"<Signal {self.strategy_id} {self.instrument} "
            f"{self.direction} @ {self.entry_price}>"
        )


class Trade(Base):
    """
    All executed and paper trades.

    Captures the full lifecycle: open, modify, close.
    R multiple is calculated at close time.
    """
    __tablename__ = "trades"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    signal_id = Column(String(36), nullable=True)    # FK to signals.id
    broker_order_id = Column(String(100), nullable=True, index=True)
    strategy_id = Column(String(100), nullable=False, index=True)
    instrument = Column(String(20), nullable=False, index=True)
    timeframe = Column(String(5), nullable=False)
    direction = Column(String(4), nullable=False)
    status = Column(String(20), nullable=False, default="OPEN", index=True)
    # Status values: OPEN | CLOSED | CANCELLED | PARTIAL

    # Prices
    entry_price = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=False)
    take_profit = Column(Float, nullable=False)
    exit_price = Column(Float, nullable=True)

    # Size & P&L
    lot_size = Column(Float, nullable=False)
    account_balance_at_open = Column(Float, nullable=True)
    pnl = Column(Float, nullable=True)
    r_multiple = Column(Float, nullable=True)
    commission = Column(Float, default=0.0)
    spread_cost = Column(Float, nullable=True)

    # Metadata
    is_paper = Column(Boolean, default=True, nullable=False)
    open_time = Column(DateTime, nullable=False, index=True)
    close_time = Column(DateTime, nullable=True)
    close_reason = Column(String(50), nullable=True)
    # Close reason: take_profit | stop_loss | manual | strategy | daily_limit
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    def __repr__(self) -> str:
        return (
            f"<Trade {self.instrument} {self.direction} "
            f"{'PAPER' if self.is_paper else 'LIVE'} "
            f"status={self.status}>"
        )


class StrategyRegistry(Base):
    """
    Registry of all strategies with metadata and live status.

    Strategies must be registered before they can generate signals.
    The 'live_status' field gates execution:
        research   — not validated, no execution
        backtested — historical validation only
        paper      — paper trading active
        live_small — small live allocation
        live       — full production
        disabled   — suspended
    """
    __tablename__ = "strategy_registry"

    id = Column(String(100), primary_key=True)   # e.g. 'ICT_SILVER_BULLET_V1'
    name = Column(String(200), nullable=False)
    version = Column(String(20), nullable=False)
    description = Column(Text, nullable=True)
    markets = Column(Text, nullable=True)        # JSON list
    timeframes = Column(Text, nullable=True)     # JSON list
    live_status = Column(String(20), default="research", index=True)
    historical_win_rate = Column(Float, nullable=True)
    profit_factor = Column(Float, nullable=True)
    max_drawdown_pct = Column(Float, nullable=True)
    sample_size = Column(Integer, nullable=True)
    last_validated = Column(DateTime, nullable=True)
    date_added = Column(DateTime, default=datetime.utcnow)
    notes = Column(Text, nullable=True)

    def __repr__(self) -> str:
        return f"<Strategy {self.id} status={self.live_status}>"


class RiskEvent(Base):
    """Records every time a risk rule is triggered or breached."""
    __tablename__ = "risk_events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    event_type = Column(String(100), nullable=False, index=True)
    # Types: daily_limit_hit | weekly_limit_hit | max_exposure | spread_limit
    #        drawdown_warning | drawdown_halt | position_size_capped
    current_value = Column(Float, nullable=True)
    limit_value = Column(Float, nullable=True)
    action_taken = Column(String(200), nullable=True)
    instrument = Column(String(20), nullable=True)
    strategy_id = Column(String(100), nullable=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)


class DailySnapshot(Base):
    """Daily end-of-day equity and performance snapshot."""
    __tablename__ = "daily_snapshots"
    __table_args__ = (UniqueConstraint("date"),)

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(String(10), nullable=False, unique=True)  # YYYY-MM-DD
    opening_balance = Column(Float, nullable=False)
    closing_balance = Column(Float, nullable=False)
    daily_pnl = Column(Float, nullable=False)
    daily_pnl_pct = Column(Float, nullable=False)
    trades_opened = Column(Integer, default=0)
    trades_closed = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    losing_trades = Column(Integer, default=0)
    largest_win = Column(Float, nullable=True)
    largest_loss = Column(Float, nullable=True)
    running_weekly_dd_pct = Column(Float, nullable=True)
    running_monthly_dd_pct = Column(Float, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)


class NotificationLog(Base):
    """Log of all sent notifications."""
    __tablename__ = "notifications_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    channel = Column(String(50), nullable=False)   # pushover | telegram | email
    notification_type = Column(String(100), nullable=False)
    title = Column(String(200), nullable=True)
    message = Column(Text, nullable=False)
    success = Column(Boolean, nullable=False)
    error = Column(String(500), nullable=True)
    timestamp = Column(DateTime, default=datetime.utcnow)


# ── Initialisation ────────────────────────────────────────────────────────────

def init_db() -> None:
    """
    Create all tables if they do not exist.

    Safe to call multiple times. Will not drop or modify existing tables.
    For schema migrations use Alembic.
    """
    engine = get_engine()
    Base.metadata.create_all(engine)
    log.info("database_initialised", tables=list(Base.metadata.tables.keys()))


def verify_db() -> bool:
    """
    Verify the database is accessible and all expected tables exist.

    Returns:
        True if all tables exist, False otherwise.
    """
    expected_tables = {
        "ohlcv", "signals", "trades", "strategy_registry",
        "risk_events", "daily_snapshots", "notifications_log",
    }
    try:
        engine = get_engine()
        with engine.connect() as conn:
            result = conn.execute(
                text("SELECT name FROM sqlite_master WHERE type='table'")
            )
            existing = {row[0] for row in result}
        missing = expected_tables - existing
        if missing:
            log.warning("database_tables_missing", missing=list(missing))
            return False
        log.info("database_verified", table_count=len(existing))
        return True
    except Exception as e:
        log.error("database_verify_failed", error=str(e))
        return False
